# Generated by Django 4.2.5 on 2023-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_finish",
            field=models.BooleanField(default=False),
        ),
    ]
