# Generated by Django 4.2.5 on 2023-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_task_is_finish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
