# Generated by Django 4.2.5 on 2023-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="todo.tag"),
        ),
    ]
