# Generated by Django 4.2.5 on 2023-10-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0006_task_end_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
