# Generated by Django 4.2.5 on 2023-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0008_task_created_at_task_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
