# Generated by Django 4.2.5 on 2023-10-06 17:28

from django.db import migrations


def set_default_category_to_task(apps, schema_editor):
    task_model = apps.get_model("todo", "Task")
    if task_model.objects.count() == 0:
        return

    category_model = apps.get_model("todo", "Category")
    default_category, _ = category_model.objects.get_or_create(name="default")
    task_model.objects.update(category=default_category)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("todo", "0010_task_category"),
    ]

    operations = [
        migrations.RunPython(
            set_default_category_to_task,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]
