# Generated by Django 4.2.5 on 2023-10-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0011_set_default_category_to_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="todo.category",
            ),
        ),
    ]
