# Generated by Django 4.2.5 on 2023-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0014_alter_task_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(blank=True, upload_to="task/attachments/"),
        ),
    ]
