# Generated by Django 4.2.5 on 2023-10-13 13:42

from django.conf import settings
from django.contrib.auth import hashers
from django.db import migrations


def set_default_category_to_task(apps, schema_editor):
    task_model = apps.get_model("todo", "Task")
    if task_model.objects.count() == 0:
        return

    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    unknown_user, _ = user_model.objects.update_or_create(
        username="unknown",
        defaults={"is_active": False, "password": hashers.make_password(None)},
    )

    task_model.objects.update(creator=unknown_user)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("todo", "0016_task_creator"),
    ]

    operations = [
        migrations.RunPython(
            set_default_category_to_task,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
    ]
